# Generated by Django 2.1.2 on 2018-11-29 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.AutoField(primary_key=True, serialize=False)),
                ('nomascota', models.CharField(max_length=30, verbose_name='Nombre Mascota')),
                ('raza', models.CharField(default='', max_length=20)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='Mascota', max_length=20)),
                ('fotografia', models.ImageField(default='', upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(default='Usuario', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
