# Generated by Django 2.1.2 on 2018-11-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0009_auto_20181111_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
